---
title: "Fallido"
output: html_notebook
---

```{r}
# Normalizamos los datos de las variables

  base_completa_N <- base_completa %>%
    mutate(across(.cols = c("ANS","DP","ESQ","BI","DA","AH","DR"),~log(.x)))
  
  base_completa_N <- base_completa_N %>% 
    group_by(paises_P) %>%
    mutate(ANS1 = c(0,diff(ANS,lag=1, differences =1)),
           DP1 = c(0,diff(DP,lag=1, differences =1)),
           ESQ1 = c(0,diff(ESQ,lag=1, differences =1)),
           BI1 = c(0,diff(BI,lag=1, differences =1)),
           DA1 = c(0,diff(DA,lag=1, differences =1)),
           AH1 = c(0,diff(AH,lag=1, differences =1)),
           DR1 = c(0,diff(DR,lag=1, differences =1)))
  
  base_completa_N <- base_completa_N %>%
    mutate(ANS1 = ANS1*100,
           DP1 = DP1*100 ,
           ESQ1 = ESQ1*100,
           BI1 = BI1*100,
           DA1 = DA1*100 ,
           AH1 = AH1*100,
           DR1 = DR1*100)
  # Ponderacion de variables 
  
  ponderadores <- lm(SU ~ ANS1+DP1+ESQ1+BI1+DA1+AH1+DR1+paises_P,data = base_completa_N)

  summary(ponderadores)
  
  cof <- ponderadores$coefficients
  
  cof1 <- cof[2:8]

  
```

#### Ponderadores

| Sub-indice | Coeficiente | Peso |
|------------|-------------|------|
| ANS        | 0.9659111   | 1/5  |
| DP         | 0.6155536   | 1/7  |
| ESQ        | -0.6864928  | 1/15 |
| BI         | 1.2827090   | 1/3  |
| DA         | -0.5513196  | 1/13 |
| AH         | 0.6183177   | 1/7  |
| DR         | -1.4240587  | 1/30 |

Se aignan pesos a cada uno de los sub-indices segun la significancia economica del coeficiente encontrado.

```{r}
  # Creacion del indice por suma aritmetica

base_completa_N <- base_completa_N %>%
  ungroup() %>%
  mutate(IHSM = ANS1*1/5+DP1*1/7+ESQ1*1/15+BI1*1/3+DA1*1/13+AH1*1/7+DR1*1/30)

base_completa_N <- select(base_completa_N, -IHSM1)



```

  
