---
title: "Taller 4"
author: Santiago López Rodríguez, Manuel Alejandro Noriega Lizarazo y Xara Lucia Chamorro
  Aristizabal
output:
  html_document:
    df_print: paged
  pdf_document: default
---

## Librerias

```{r}
library("tidyverse")
library("naniar")
library("ggthemes")
library("readxl")
library("lubridate")
library("dplyr")
```

## Punto 1

```{r}
IHSM <- read_delim("Datos/IHSM.csv", delim = ";")
regresion_1 <- read_delim("Datos/Regresion_1.csv", delim = ";")
regresion_2 <- read_delim("Datos/Regresion_2.csv", delim = ";")
Paises <- read_excel("Datos/PAISES.xlsx")
IDH <- read_delim("Datos/IDH.csv",";")
IDH <- IDH %>% 
  mutate(IDH = IDH*100)

```

## Punto 3

```{r}
IHSM <- left_join(IHSM, regresion_1, by = c("paises_P","ano"))
IHSM <- left_join(IHSM, regresion_2, by = c("paises_P","ano"))
IHSM <- left_join(IHSM, Paises,by = "paises_P")
IHSM <- left_join(IHSM, IDH,by = c("paises_P","ano"))
```

## Punto 4

```{r}
IHSM <- IHSM %>% 
  mutate(across(.cols = c("paises_P","codigo","IncomeGroup"),~as.factor(.x)))
```

## Punto 5

```{r}
##  Creamos la variable IHSM 

  # Consideramos la fiabilidad de las variables, con un indicador de suma 

  IHSM <- IHSM %>% 
  mutate(suma = ANS+DP+ESQ+BI+DA+AH+DR)

  # Alfa de Cronbach

  for (i in 4:10) {
  dato <- var(IHSM[i],na.rm = TRUE)
  print(dato)
  }

  # Prueba

  varianza_variables <-1.363118+0.4301509+0.00195831+0.02944265+0.02500865+0.8292454+3.417732
    
  varianza_indicador <- var(IHSM$suma,na.rm = TRUE)
  v <- 7
    
  cronbach <- function(v,v1,v2){
    cosa <- v/(v-1)
    resto <- (v2-v1)/v2
    print(cosa*resto)
  }
  
  # Fiabilidad
  cronbach(v,varianza_variables,varianza_indicador)

  ## la fiabilida superior a 0.70 es lo preferible, como sale 0.6959472, se plantea como aceptable
  
rm(list= c("dato","regresion_1","regresion_2","i","v","varianza_variables","varianza_indicador"))

base_completa <- IHSM %>% select(-suma)

  # Remplazamos valores faltantes en las variables del indicador

# Solo AH contiene valores faltantes
vis_miss(base_completa)

# Remplazo
base_completa <- base_completa %>% 
  group_by(paises_P)

base_completa <- fill(base_completa, AH)

base_completa <- drop_na(base_completa, AH)

base_completa <- select(base_completa,-codigo)

```

### Damos valores de normalizacion

```{r}
# Valores minimos de los sub-índices
for (i in 3:9) {
  minimo<-min(base_completa[i])
  print(minimo)
}
# Valores maximos de los sub-índices
for (i in 3:9) {
  maximo<-max(base_completa[i])
  print(maximo)
}
```

| Indicador | Valor Maximo | Valor minimo |
|-----------|--------------|--------------|
| ANS       | 8.96733      | 2.023393     |
| DP        | 6.602754     | 2.139903     |
| ESQ       | 0.3751096    | 0.1469018    |
| BI        | 1.206597     | 0.3145345    |
| DA        | 0.9439906    | 0.07390753   |
| AH        | 6.933015     | 1.196984     |
| DR        | 19.11546     | 9.715255     |

```{r}
# Calculamos los sub-indices respecto a los valores minimox y maximos
base_completa <- base_completa %>%
     mutate(ANS_a = (ANS-2.023393)/(8.96733-2.023393),
           DP_a = (DP-2.139903)/(6.602754-2.139903),
           ESQ_a = (ESQ-0.1469018)/(0.3751096-0.1469018),
           BI_a = (BI-0.3145345)/(1.206597-0.3145345),
           DA_a = (DA-0.07390753)/(0.9439906-0.07390753),
           AH_a = (AH-1.196984)/(6.933015-1.196984),
           DR_a = (DR-9.715255)/(19.11546-9.715255))

# Calaculamos el indice IHSM
base_completa <- base_completa %>%
  mutate(IHSM = ANS_a*1/7+DP_a*1/7+ESQ_a*1/7+BI_a*1/7+DA_a*1/7+AH_a*1/7+DR_a*1/7)

arrange(base_completa,desc(IHSM))

# Se multiplican los resultados de IHSM por 100.
base_completa<- base_completa %>%
    mutate(IHSM = IHSM*100)

# Creamos un IHSM ajustado por region de ingreso para mejorar la capacidad del instrumento debido a sesgos en los datos de salud mental, presente por la mala recoleccion de datos de paises de ingreso bajo y medio.

base_completa <- base_completa %>%
  ungroup() %>%
  group_by(IncomeGroup)%>%
  mutate(IHSM_ajustado = ((IHSM- min(IHSM))/(max(IHSM)-min(IHSM))*100))

# Desarupamos y eliminamos los datos faltantes por region de ingreso
base_completa<- tibble(base_completa)

base_completa1 <- drop_na(base_completa,IncomeGroup)

class(base_completa1)
```

### Estadistica Descritiva

```{r}
# Estadisticas descriptivas 
resumen_paises <- base_completa1 %>%
    group_by(paises_P)%>%  
    summarize(across(.cols = c("IHSM_ajustado","GINId","IC","IDH","GPS","GPE","GPD"), list(Media=~mean(.x,na.rm = T), DesviacionEstandar=~sd(.x,na.rm = T), Maximo=~max(.x,na.rm = T), Minimo=~min(.x,na.rm = T), Mediana=~median(.x,na.rm = T)))) %>%
      ungroup()

```

## Punto 6

```{r}
# Histogramas de la variable dependiente, e independientes principales
base_completa1 <- base_completa1 %>%
  mutate(IncomeGroup = recode(IncomeGroup,"High income"= "Alto","Upper middle income" = "Medio Alto","Lower middle income" = "Medio Bajo","Low income" = "Bajo"))


## IHSM
ggplot(data = base_completa1, 
       mapping = aes(x= IHSM_ajustado,color = IncomeGroup)) + 
    geom_histogram( fill = "lightseagreen",bins = 100)+
    labs(title = "Histograma de IHSM", subtitle = "Índice Humano de Salud Mental",y = "Frecuencia" , caption = "Produccion Propia")+
    theme_classic()

##GINId
ggplot(data = base_completa1, 
       mapping = aes(x= GINId,color = IncomeGroup)) + 
    geom_histogram(fill = "lightcyan3",bins = 100)+
    labs(title = "Histograma de GINI", subtitle = "Despues de impuestos",y = "Frecuencia" , caption = "Banco Mundial")+
    theme_classic()

## IC
ggplot(data = base_completa1, 
       mapping = aes(x= IC,color = IncomeGroup)) + 
    geom_histogram(fill = "lightcyan3",bins = 100)+
    labs(title = "Histograma de Índice de Percepcion de la Corrupcion",y = "Frecuencia" , caption = "DatosMacro")+
    theme_classic()

## IDH
ggplot(data = base_completa1, 
       mapping = aes(x= IDH,color = IncomeGroup)) + 
    geom_histogram(fill = "lightcyan3",bins = 100)+
    labs(title = "Histograma de Índice de Desarrollo Humano",y = "Frecuencia", caption = "DatosMacro")+
    theme_classic()

## GPS
ggplot(data = base_completa1, 
       mapping = aes(x= GPS,color = IncomeGroup)) + 
    geom_histogram(fill = "lightcyan3",bins = 100)+
    labs(title = "Histograma de Gasto Publico en Salud",y = "Frecuencia", caption = "DatosMacro")+
    theme_classic()

## GPE
ggplot(data = base_completa1, 
       mapping = aes(x= GPE,color = IncomeGroup)) + 
    geom_histogram( fill = "lightcyan3",bins = 100)+
    labs(title = "Histograma de Gasto Publico en Educacion",y = "Frecuencia", caption = "DatosMacro")+
    theme_classic()

## GPD
ggplot(data = base_completa1, 
       mapping = aes(x= GPD,color = IncomeGroup)) + 
    geom_histogram(fill = "lightcyan3",bins = 75)+
    labs(title = "Histograma de Gasto Publico en Defensa",y = "Frecuencia", caption = "DatosMacro")+
    theme_classic()

## IncomeGroup
ggplot(data = base_completa1,
       mapping = aes(x = IncomeGroup)) +
  geom_bar(color = "mediumblue", fill = "white")+
  labs(title = "Diagrama de Barras de Grupo de Ingreso",y = "Frecuencia",x= "Niveles de ingreso", caption = "DatosMacro")+
    theme_classic()
  
```

## Punto 7

```{r}
# Correlalograma
variables_cor <- base_completa1 %>% select(IHSM_ajustado,GINId,IC,IDH,GPS,GPE,GPD)

cor(variables_cor,  use = "complete.obs")
```

## Punto 8

```{r}
# GINId
ggplot(data = base_completa1, 
       mapping = aes(x = IHSM_ajustado,
                     y = GINId)) +
  geom_point(aes(color= IncomeGroup))+
     geom_smooth(method = "lm")+
  labs(title = "Entre mayor es el GINI", subtitle = "debilmente mayor es el Indice Humano de Salud Mental", x = "Indice Humano de Salud Mental", y = "GINI despues de impuestos", caption = "Produccion Propia", color= "Grupo de Ingreso")+
  theme_classic()

# IC
ggplot(data = base_completa1, 
       mapping = aes(x = IHSM_ajustado,
                     y = IC)) +
  geom_point(aes(color= IncomeGroup))+
     geom_smooth(method = "lm")+
  labs(title = "Entre mayor es el Índice de Percepcion de la Corrupcion", subtitle = "mayor es el Indice Humano de Salud Mental", x = "Indice Humano de Salud Mental", y = "Índice de Percepcion de la Corrupcion", caption = "Produccion Propia", color= "Grupo de Ingreso")+
  theme_classic()

# IDH

ggplot(data = base_completa1, 
       mapping = aes(x = IHSM_ajustado,
                     y = IDH)) +
  geom_point(aes(color= IncomeGroup))+
     geom_smooth(method = "lm")+
  labs(title = "Entre mayor es el Índice de Desarrollo Humano", subtitle = "mayor es el Indice Humano de Salud Mental", x = "Indice Humano de Salud Mental", y = "Índice de Desarrollo Humano", caption = "Produccion Propia", color= "Grupo de Ingreso")+
  theme_classic()

# GPS

ggplot(data = base_completa1, 
       mapping = aes(x = IHSM_ajustado,
                     y = GPS)) +
  geom_point(aes(color= IncomeGroup))+
     geom_smooth(method = "lm")+
  labs(title = "Entre mayor es Gasto Publico en Salud", subtitle = "mayor es el Indice Humano de Salud Mental", x = "Indice Humano de Salud Mental", y = "Gasto Publico en Salud", caption = "Produccion Propia", color= "Grupo de Ingreso")+
  theme_classic()

# GPE

ggplot(data = base_completa1, 
       mapping = aes(x = IHSM_ajustado,
                     y = GPE)) +
  geom_point(aes(color= IncomeGroup))+
     geom_smooth(method = "lm")+
  labs(title = "Entre mayor es Gasto Publico en Educacion", subtitle = "mayor es el Indice Humano de Salud Mental", x = "Indice Humano de Salud Mental", y = "Gasto Publico en Educacion", caption = "Produccion Propia", color= "Grupo de Ingreso")+
  theme_classic()

# GPD

ggplot(data = base_completa1, 
       mapping = aes(x = IHSM_ajustado,
                     y = GPD)) +
  geom_point(aes(color= IncomeGroup))+
     geom_smooth(method = "lm")+
  labs(title = "Entre mayor es Gasto Publico en Defensa", subtitle = "debilmente mayor es el Indice Humano de Salud Mental", x = "Indice Humano de Salud Mental", y = "Gasto Publico en Defensa", caption = "Produccion Propia", color= "Grupo de Ingreso")+
  theme_classic()
```

